'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.18063
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option or rebuild the Visual Studio project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class _Global
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Resources.Global", Global.System.Reflection.[Assembly].Load("App_GlobalResources"))
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to La tâche est en cours d&apos;exécution. Veuillez attendre qu&apos;elle soit terminée. Merci..
        '''</summary>
        Friend Shared ReadOnly Property MessagePostBack() As String
            Get
                Return ResourceManager.GetString("MessagePostBack", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;p style=&apos;&apos;&gt;&lt;span style=&apos;font-size:16px; color:#ff3700; font-weight:bolder;&apos;&gt;Conditions d&apos;utilisation&lt;/span&gt;&lt;/p&gt;
        '''
        '''&lt;br /&gt;&lt;p style=&apos;&apos;&gt;&lt;b&gt;&lt;span style=&apos;&apos;&gt;Introduction&lt;/span&gt;&lt;/b&gt;&lt;/p&gt;
        '''
        '''&lt;p style=&apos;&apos;&gt;
        '''&lt;span style=&apos;&apos;&gt;Industeel Belgium s.a. exploite ce site Web (le «site Web») pour fournir un accès en ligne aux informations et documents relatifs aux commandes des clients.&lt;/span&gt;
        '''&lt;/p&gt;
        '''
        '''&lt;p style=&apos;&apos;&gt;&lt;span style=&apos;&apos;&gt;Veuillez s&apos;il vous plaît lire les termes et conditions énoncées dans le présent document (les «condi [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property TexteConditions() As String
            Get
                Return ResourceManager.GetString("TexteConditions", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Veuillez patienter.
        '''</summary>
        Friend Shared ReadOnly Property TitreMessagePostBack() As String
            Get
                Return ResourceManager.GetString("TitreMessagePostBack", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
