'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Contact

    '''<summary>
    '''lblTitreGlobal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTitreGlobal As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblTitreOperateur control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTitreOperateur As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''dlsOperateur control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dlsOperateur As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''lblTitreHelpdesk control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTitreHelpdesk As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblHelpdeskMessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblHelpdeskMessage As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblHelpDescEmailLibelle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblHelpDescEmailLibelle As Global.System.Web.UI.WebControls.Label
End Class
