'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Redefinition

    '''<summary>
    '''lblTitreGlobal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTitreGlobal As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblTitreSecondaire control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTitreSecondaire As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''wcuNotification control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents wcuNotification As Global.UIWebeKPI.ValidatorSummaryControl

    '''<summary>
    '''tblNouveauMotPasse control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblNouveauMotPasse As Global.System.Web.UI.HtmlControls.HtmlTable

    '''<summary>
    '''lblLoginEmailLibelle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLoginEmailLibelle As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblLogin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLogin As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblAncienMotPasse control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAncienMotPasse As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtAncienMotPasse control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAncienMotPasse As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''rfvAncienMotPasse control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvAncienMotPasse As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''lblNouveauMotPasse control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNouveauMotPasse As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtNouveauMotPasse control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNouveauMotPasse As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''cpvNouveauMotPasse control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cpvNouveauMotPasse As Global.System.Web.UI.WebControls.CompareValidator

    '''<summary>
    '''rfvNouveauMotPasse control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvNouveauMotPasse As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''revMotPasse control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents revMotPasse As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''lblNouveauMotPasseConfirmation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNouveauMotPasseConfirmation As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtNouveauMotPasseConfirmation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNouveauMotPasseConfirmation As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''rfvNouveauMotPasseConfirmation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvNouveauMotPasseConfirmation As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''cevConfirmacion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cevConfirmacion As Global.System.Web.UI.WebControls.CompareValidator

    '''<summary>
    '''btnValider control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnValider As Global.System.Web.UI.WebControls.Button
End Class
