'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class AfficherHistoriqueObjectifLivraison

    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''lblDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDescription As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDescription As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblCommandeStandartMoinsDeuxPlusZero control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCommandeStandartMoinsDeuxPlusZero As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtCommandeStandardMoinsDeuxPlusZero control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCommandeStandardMoinsDeuxPlusZero As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblCommandePackMoinsZeroPlusZero control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCommandePackMoinsZeroPlusZero As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtCommandePackMoinsZeroPlusZero control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCommandePackMoinsZeroPlusZero As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblCommandeStandartMoinsDeuxPlusDeux control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCommandeStandartMoinsDeuxPlusDeux As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtCommandeStandardMoinsDeuxPlusDeux control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCommandeStandardMoinsDeuxPlusDeux As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblCommandePackMoinsZeroPlusUn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCommandePackMoinsZeroPlusUn As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtCommandePackMoinsZeroPlusUn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCommandePackMoinsZeroPlusUn As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnValider control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnValider As Global.System.Web.UI.WebControls.Button
End Class
