'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ConfigurationObjectif

    '''<summary>
    '''lblTitreGlobal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTitreGlobal As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblTitreSecondaire control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTitreSecondaire As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblVersionActuelle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblVersionActuelle As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDescription As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDescription As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblCommandeStandartMoinsDeuxPlusZero control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCommandeStandartMoinsDeuxPlusZero As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtCommandeStandardMoinsDeuxPlusZero control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCommandeStandardMoinsDeuxPlusZero As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''rfvCommandeStandardMoinsDeuxPlusZero control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvCommandeStandardMoinsDeuxPlusZero As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''lblCommandePackMoinsZeroPlusZero control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCommandePackMoinsZeroPlusZero As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtCommandePackMoinsZeroPlusZero control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCommandePackMoinsZeroPlusZero As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''rfvCommandePackMoinsZeroPlusZero control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvCommandePackMoinsZeroPlusZero As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''lblCommandeStandartMoinsDeuxPlusDeux control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCommandeStandartMoinsDeuxPlusDeux As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtCommandeStandardMoinsDeuxPlusDeux control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCommandeStandardMoinsDeuxPlusDeux As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''rfvCommandeStandardMoinsDeuxPlusDeux control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvCommandeStandardMoinsDeuxPlusDeux As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''lblCommandePackMoinsZeroPlusUn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCommandePackMoinsZeroPlusUn As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtCommandePackMoinsZeroPlusUn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCommandePackMoinsZeroPlusUn As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''rfvCommandePackMoinsZeroPlusUn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvCommandePackMoinsZeroPlusUn As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''btnValider control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnValider As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblHistorique control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblHistorique As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''gvwConfigurationObjectifLivraison control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvwConfigurationObjectifLivraison As Global.System.Web.UI.WebControls.GridView
End Class
